CUDA_VISIBLE_DEVICES=0 python test.py \
               --root_path ~/brain4cars/bky40/code \
               --video_path brain4cars_data \
               --annotation_path datasets/annotation \
			   --resume_path results/ \
			   --dataset Brain4cars_Unit \
			   --batch_size 1 \
			   --n_threads 4 \
			   --checkpoint 5  \
			   --n_epochs 100 \
			   --begin_epoch 1 \
			   --sample_duration 10 \
			   --end_second 0 \
			   --interval 16 \
			   --n_scales 1 \
			   --norm_value 255 \
			   --n_fold -1 \
			   --train_from_scratch 0 \
			   --last_epoch 5 \
               --test_start_epoch 5 \
               --test_end_epoch 100 \

